// <auto-generated />
using System;
using FYP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FYP.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260814002452_AddBuyerWishlist")]
    partial class AddBuyerWishlist
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FYP.Models.Entities.Address", b =>
                {
                    b.Property<int>("AddressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AddressID"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("HouseBuildingStreet")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(10, 7)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(10, 7)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("StateArea")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UnitNumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("AddressID");

                    b.HasIndex("UserID");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("FYP.Models.Entities.AuditLog", b =>
                {
                    b.Property<string>("LogID")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("IP_Address")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("LogID");

                    b.HasIndex("UserID");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("FYP.Models.Entities.BlacklistedImageHash", b =>
                {
                    b.Property<int>("HashID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("HashID"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("AddedByAdminID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SHA256Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("HashID");

                    b.HasIndex("AddedByAdminID");

                    b.ToTable("BlacklistedImageHashes");
                });

            modelBuilder.Entity("FYP.Models.Entities.Cart", b =>
                {
                    b.Property<string>("CartID")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("CartID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("FYP.Models.Entities.CartItem", b =>
                {
                    b.Property<string>("CartItemID")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CartID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ProductID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("CartItemID");

                    b.HasIndex("CartID");

                    b.HasIndex("ProductID");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("FYP.Models.Entities.Category", b =>
                {
                    b.Property<string>("CategoryID")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("IconSvg")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("CategoryID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = "cat_tech_1",
                            Description = "Latest gadgets, electronics, and smart devices.",
                            IconSvg = "<svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"><rect x=\"4\" y=\"4\" width=\"16\" height=\"16\" rx=\"2\"></rect><rect x=\"9\" y=\"9\" width=\"6\" height=\"6\"></rect><line x1=\"9\" y1=\"1\" x2=\"9\" y2=\"4\"></line><line x1=\"15\" y1=\"1\" x2=\"15\" y2=\"4\"></line><line x1=\"9\" y1=\"20\" x2=\"9\" y2=\"23\"></line><line x1=\"15\" y1=\"20\" x2=\"15\" y2=\"23\"></line><line x1=\"20\" y1=\"9\" x2=\"23\" y2=\"9\"></line><line x1=\"20\" y1=\"14\" x2=\"23\" y2=\"14\"></line><line x1=\"1\" y1=\"9\" x2=\"4\" y2=\"9\"></line><line x1=\"1\" y1=\"14\" x2=\"4\" y2=\"14\"></line></svg>",
                            Name = "Tech & Gadgets"
                        });
                });

            modelBuilder.Entity("FYP.Models.Entities.ChatMessage", b =>
                {
                    b.Property<string>("ChatID")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("AttachmentType")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("AttachmentUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("NLP_Flag")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ReceiverID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SenderID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ChatID");

                    b.HasIndex("ReceiverID");

                    b.HasIndex("SenderID");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("FYP.Models.Entities.Courier", b =>
                {
                    b.Property<string>("CourierID")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TrackingUrlTemplate")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("CourierID");

                    b.ToTable("Couriers");

                    b.HasData(
                        new
                        {
                            CourierID = "COUR_JNT",
                            IsActive = true,
                            Name = "J&T Express",
                            TrackingUrlTemplate = "https://www.jtexpress.my/tracking/{0}"
                        },
                        new
                        {
                            CourierID = "COUR_POS",
                            IsActive = true,
                            Name = "PosLaju",
                            TrackingUrlTemplate = "https://track.pos.com.my/tracking/{0}"
                        });
                });

            modelBuilder.Entity("FYP.Models.Entities.Delivery", b =>
                {
                    b.Property<string>("DeliveryID")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ActualDeliveryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CourierID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("EstimatedDeliveryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OrderID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("ShippingFee")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("DeliveryID");

                    b.HasIndex("CourierID");

                    b.HasIndex("OrderID");

                    b.ToTable("Deliveries");
                });

            modelBuilder.Entity("FYP.Models.Entities.DeliveryPricingRule", b =>
                {
                    b.Property<string>("DeliveryRuleID")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("BaseWeightKg")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("CourierID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("IncrementalPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("IncrementalWeightKg")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("ZoneRegion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("DeliveryRuleID");

                    b.HasIndex("CourierID");

                    b.ToTable("DeliveryPricingRules");

                    b.HasData(
                        new
                        {
                            DeliveryRuleID = "RULE_JNT_WM",
                            BasePrice = 4.90m,
                            BaseWeightKg = 1.00m,
                            CourierID = "COUR_JNT",
                            IncrementalPrice = 1.00m,
                            IncrementalWeightKg = 0.50m,
                            ZoneRegion = "West Malaysia"
                        },
                        new
                        {
                            DeliveryRuleID = "RULE_JNT_EM",
                            BasePrice = 12.00m,
                            BaseWeightKg = 1.00m,
                            CourierID = "COUR_JNT",
                            IncrementalPrice = 2.50m,
                            IncrementalWeightKg = 0.50m,
                            ZoneRegion = "East Malaysia"
                        },
                        new
                        {
                            DeliveryRuleID = "RULE_POS_WM",
                            BasePrice = 6.00m,
                            BaseWeightKg = 2.00m,
                            CourierID = "COUR_POS",
                            IncrementalPrice = 1.50m,
                            IncrementalWeightKg = 1.00m,
                            ZoneRegion = "West Malaysia"
                        },
                        new
                        {
                            DeliveryRuleID = "RULE_POS_EM",
                            BasePrice = 10.00m,
                            BaseWeightKg = 1.00m,
                            CourierID = "COUR_POS",
                            IncrementalPrice = 3.00m,
                            IncrementalWeightKg = 0.50m,
                            ZoneRegion = "East Malaysia"
                        });
                });

            modelBuilder.Entity("FYP.Models.Entities.DeviceLockout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceIdentifier")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceIdentifier")
                        .IsUnique();

                    b.ToTable("DeviceLockouts");
                });

            modelBuilder.Entity("FYP.Models.Entities.FraudAlert", b =>
                {
                    b.Property<string>("AlertID")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OrderID")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("RiskScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("SHAP_Data")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("AlertID");

                    b.HasIndex("OrderID")
                        .IsUnique();

                    b.ToTable("FraudAlerts");
                });

            modelBuilder.Entity("FYP.Models.Entities.HelpArticle", b =>
                {
                    b.Property<int>("HelpArticleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("HelpArticleID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("HelpCategoryID")
                        .HasColumnType("int");

                    b.Property<bool>("IsPopular")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("HelpArticleID");

                    b.HasIndex("HelpCategoryID");

                    b.ToTable("HelpArticles");

                    b.HasData(
                        new
                        {
                            HelpArticleID = 1,
                            Content = "<h4>Creating Your SecurePlatform Account</h4><p>Follow these simple steps to get started:</p><ol><li>Click the <strong>Sign Up</strong> button at the top right corner of the homepage.</li><li>Enter your email address and create a strong password. Your password must contain at least 8 characters, including uppercase, lowercase, numbers, and special characters.</li><li>Verify your email address by entering the OTP (One-Time Password) sent to your inbox.</li><li>Complete your profile by adding your name and phone number.</li></ol><p>Once verified, you can start browsing and purchasing products immediately!</p>",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HelpCategoryID = 1,
                            IsPopular = false,
                            Title = "How to create an account?"
                        },
                        new
                        {
                            HelpArticleID = 2,
                            Content = "<h4>Troubleshooting OTP Issues</h4><p>If you haven't received your OTP, try the following:</p><ul><li><strong>Check your Spam/Junk folder</strong> — OTP emails sometimes get filtered by email providers.</li><li><strong>Wait a moment</strong> — OTPs can take up to 2 minutes to arrive depending on your email provider.</li><li><strong>Verify your email address</strong> — Make sure the email address you entered is correct with no typos.</li><li><strong>Request a new OTP</strong> — Click the 'Resend OTP' button on the verification page.</li></ul><p>If you continue to experience issues, please contact our support team via the live chat.</p>",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HelpCategoryID = 1,
                            IsPopular = true,
                            Title = "Why did I not receive my OTP?"
                        },
                        new
                        {
                            HelpArticleID = 3,
                            Content = "<h4>Resetting Your Password</h4><p>If you've forgotten your password, follow these steps:</p><ol><li>Go to the <strong>Login</strong> page and click <em>'Forgot Password?'</em>.</li><li>Enter the email address associated with your account.</li><li>You will receive an OTP on your email. Enter the OTP to verify your identity.</li><li>Create a new password that meets our security requirements (minimum 8 characters with uppercase, lowercase, number, and special character).</li></ol><p><strong>Tip:</strong> If you have TOTP (Authenticator App) enabled, you can also verify using your authenticator code for faster access.</p>",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HelpCategoryID = 1,
                            IsPopular = false,
                            Title = "How to reset my password?"
                        },
                        new
                        {
                            HelpArticleID = 4,
                            Content = "<h4>Staying Safe on SecurePlatform</h4><p>Our platform uses <strong>AI-powered fraud detection</strong> (XGBoost model) to monitor transactions, but here are tips to protect yourself:</p><ul><li><strong>Never share your password or OTP</strong> with anyone — our staff will never ask for these.</li><li><strong>Check seller ratings and reviews</strong> before making a purchase.</li><li><strong>Be cautious of deals that seem too good to be true</strong> — extremely low prices may indicate fraudulent listings.</li><li><strong>Always pay through the platform</strong> — never transfer money directly to a seller outside of SecurePlatform.</li><li><strong>Enable Two-Factor Authentication (TOTP)</strong> in your account settings for an extra layer of security.</li></ul><p>If you suspect fraudulent activity, report it immediately through our chat support.</p>",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HelpCategoryID = 1,
                            IsPopular = false,
                            Title = "How to spot scams and buy safely"
                        },
                        new
                        {
                            HelpArticleID = 5,
                            Content = "<h4>Supported Payment Methods</h4><p>SecurePlatform supports the following secure payment options:</p><ul><li><strong>Credit / Debit Card</strong> — Visa, Mastercard, and other major cards are accepted. All card data is encrypted and tokenized for security. You can also save cards for faster checkout.</li><li><strong>Online Banking (FPX)</strong> — Pay directly from your Malaysian bank account via FPX. Supported banks include Maybank, CIMB, Public Bank, RHB, Hong Leong Bank, and more.</li></ul><p>All payments are processed through secure, PCI-compliant channels with end-to-end encryption.</p>",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HelpCategoryID = 2,
                            IsPopular = true,
                            Title = "What payment methods are supported?"
                        },
                        new
                        {
                            HelpArticleID = 6,
                            Content = "<h4>Common Reasons for Payment Failure</h4><p>If your payment was declined, it could be due to:</p><ul><li><strong>Insufficient funds</strong> — Ensure your account has enough balance to cover the order total including shipping fees.</li><li><strong>Card expired or blocked</strong> — Check with your bank if your card is active and enabled for online transactions.</li><li><strong>Incorrect card details</strong> — Double-check your card number, expiry date, and CVV.</li><li><strong>Bank security block</strong> — Some banks may flag unfamiliar online transactions. Contact your bank to authorize the payment.</li><li><strong>AI Security Block</strong> — Our fraud detection system may flag high-risk transactions. If your order was blocked, you will see a notification explaining the reason.</li></ul><p>You can retry the payment or try a different payment method.</p>",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HelpCategoryID = 2,
                            IsPopular = false,
                            Title = "Why did my payment fail?"
                        },
                        new
                        {
                            HelpArticleID = 7,
                            Content = "<h4>FPX Payment Flow</h4><p>FPX (Financial Process Exchange) allows you to pay directly from your bank account:</p><ol><li>At checkout, select <strong>Online Banking (FPX)</strong> as your payment method.</li><li>Choose your bank from the list of supported banks.</li><li>You will be redirected to your bank's secure login page.</li><li>Log in to your online banking and authorize the payment.</li><li>Once approved, you will be redirected back to SecurePlatform with a payment confirmation.</li></ol><p><strong>Important:</strong> Never close the browser window during the FPX process. If the session is interrupted, the payment may still be deducted. Contact us if this happens and we will investigate.</p>",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HelpCategoryID = 2,
                            IsPopular = false,
                            Title = "How does the FPX authorization process work?"
                        },
                        new
                        {
                            HelpArticleID = 8,
                            Content = "<h4>Tracking Your Order</h4><p>You can track your order at every stage of the delivery process:</p><ol><li>Go to <strong>My Purchases</strong> from your profile dropdown menu.</li><li>Find your order and click on it to open the <strong>Order Details</strong> page.</li><li>The order timeline shows real-time status updates: <em>Processing, Shipped, In Transit, Delivered</em>.</li><li>A tracking number is generated once the courier picks up your parcel. Use this to track on the courier website.</li></ol><p>You will also receive notifications at each stage of the delivery process.</p>",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HelpCategoryID = 3,
                            IsPopular = true,
                            Title = "How can I track my order status?"
                        },
                        new
                        {
                            HelpArticleID = 9,
                            Content = "<h4>Changing Your Shipping Address</h4><p>Unfortunately, once an order has been placed and payment is confirmed, the shipping address <strong>cannot be changed</strong> as the order is immediately queued for processing.</p><p><strong>What you can do:</strong></p><ul><li>If the order is still in <em>Processing</em> status, contact the seller via our chat system to request a cancellation. Then place a new order with the correct address.</li><li>Make sure to update your default address in <strong>My Account, Addresses</strong> before placing future orders.</li></ul><p><strong>Tip:</strong> Always double-check your selected delivery address on the checkout page before confirming your order.</p>",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HelpCategoryID = 3,
                            IsPopular = false,
                            Title = "How to change my shipping address after ordering?"
                        },
                        new
                        {
                            HelpArticleID = 10,
                            Content = "<h4>Shipping Fee Calculation</h4><p>Shipping fees on SecurePlatform are calculated dynamically based on:</p><ul><li><strong>Parcel weight</strong> — Each product has a weight value. The total weight of all items in your order determines the base shipping fee.</li><li><strong>Delivery zone</strong> — Your address is classified as either <em>West Malaysia</em> or <em>East Malaysia</em>. East Malaysia deliveries have higher base rates.</li><li><strong>Courier pricing rules</strong> — We compare rates from available couriers (J and T Express, PosLaju) and automatically assign the most affordable option.</li></ul><h5>Shipping Discounts</h5><ul><li>Orders above <strong>RM 600</strong> (under 5kg) — <em>Free shipping!</em></li><li>Orders above <strong>RM 500</strong> (10kg+) — <strong>RM 10 off</strong> shipping.</li><li>Orders above <strong>RM 100</strong> — <strong>RM 5 off</strong> shipping.</li></ul>",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HelpCategoryID = 3,
                            IsPopular = false,
                            Title = "How are shipping fees calculated?"
                        },
                        new
                        {
                            HelpArticleID = 11,
                            Content = "<h4>Requesting a Refund/Return</h4><p>If you are not satisfied with your purchase, you can request a refund:</p><ol><li>Go to <strong>My Purchases</strong> and find the order.</li><li>Click on the order to open <strong>Order Details</strong>.</li><li>Click the <strong>Request Refund</strong> button (available after order is received).</li><li>Select your reason for the return and choose your preferred return method: <em>Pick-Up</em> (courier comes to you) or <em>Drop-Off</em> (you drop it at a branch).</li><li>Upload photos as evidence if the product is damaged or incorrect.</li><li>Submit the request and wait for seller approval.</li></ol><p>Once approved, a courier will be assigned for pick-up or you will receive drop-off instructions.</p>",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HelpCategoryID = 4,
                            IsPopular = true,
                            Title = "How do I request a refund or return?"
                        },
                        new
                        {
                            HelpArticleID = 12,
                            Content = "<h4>Refund for Cancelled Orders</h4><p>Refunds are processed based on your original payment method:</p><ul><li><strong>Credit / Debit Card</strong> — The refund will be credited back to the same card within 7-14 business days, depending on your bank.</li><li><strong>Online Banking (FPX)</strong> — Refunds are processed back to your bank account within 5-10 business days.</li></ul><p><strong>Tracking your refund:</strong></p><ol><li>Go to <strong>My Purchases</strong> and click on the refunded order.</li><li>The refund status will show: <em>Requested, Approved, Refund In Transit, Completed</em>.</li></ol><p>If your refund has not arrived after the stated timeframe, please contact our support team.</p>",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HelpCategoryID = 4,
                            IsPopular = true,
                            Title = "How will I get my refund for cancelled orders?"
                        },
                        new
                        {
                            HelpArticleID = 13,
                            Content = "<h4>Refund Processing Timeline</h4><table style='width:100%; border-collapse:collapse; margin:15px 0;'><thead><tr style='background:#f8f9fa; border-bottom:2px solid #dee2e6;'><th style='padding:10px; text-align:left;'>Stage</th><th style='padding:10px; text-align:left;'>Estimated Time</th></tr></thead><tbody><tr style='border-bottom:1px solid #dee2e6;'><td style='padding:10px;'>Seller Review and Approval</td><td style='padding:10px;'>1-3 business days</td></tr><tr style='border-bottom:1px solid #dee2e6;'><td style='padding:10px;'>Return Shipping (if applicable)</td><td style='padding:10px;'>3-5 business days</td></tr><tr style='border-bottom:1px solid #dee2e6;'><td style='padding:10px;'>Refund Processing</td><td style='padding:10px;'>1-2 business days after item received</td></tr><tr style='border-bottom:1px solid #dee2e6;'><td style='padding:10px;'>Bank Processing (Card)</td><td style='padding:10px;'>7-14 business days</td></tr><tr><td style='padding:10px;'>Bank Processing (FPX)</td><td style='padding:10px;'>5-10 business days</td></tr></tbody></table><p>Total estimated time: <strong>12-24 business days</strong> from request to refund in your account.</p>",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HelpCategoryID = 4,
                            IsPopular = false,
                            Title = "How long does the refund process take?"
                        },
                        new
                        {
                            HelpArticleID = 14,
                            Content = "<h4>SecurePlatform Privacy Policy</h4><p>We take your privacy seriously. Here is how we handle your data:</p><h5>Data We Collect</h5><ul><li><strong>Account information</strong> — Name, email, phone number for account management.</li><li><strong>Payment data</strong> — Card details are encrypted and tokenized; we never store raw card numbers.</li><li><strong>Transaction history</strong> — Order records for your purchase history and our fraud prevention systems.</li><li><strong>Device information</strong> — Device fingerprints for security and anti-fraud measures.</li></ul><h5>How We Use Your Data</h5><ul><li>Processing your orders and payments securely.</li><li>AI-powered fraud detection to protect your account.</li><li>Sending order status updates and important notifications.</li><li>Improving our platform and user experience.</li></ul><h5>Your Rights</h5><p>You can request access to, correction of, or deletion of your personal data at any time by contacting our support team.</p>",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HelpCategoryID = 5,
                            IsPopular = false,
                            Title = "Privacy Policy"
                        },
                        new
                        {
                            HelpArticleID = 15,
                            Content = "<h4>SecurePlatform Terms of Service</h4><h5>1. Account Responsibility</h5><p>You are responsible for maintaining the confidentiality of your account credentials. Any activity under your account is your responsibility. Enable Two-Factor Authentication for enhanced security.</p><h5>2. Purchasing</h5><p>All prices are in Malaysian Ringgit (RM). Prices include product cost but shipping fees are calculated separately at checkout. Orders are binding once payment is confirmed.</p><h5>3. Seller Obligations</h5><p>Sellers must provide accurate product descriptions and images. Sellers must process and ship orders within 3 business days. Failure to do so may result in automatic cancellation.</p><h5>4. Prohibited Activities</h5><ul><li>Creating multiple accounts to exploit promotions.</li><li>Selling counterfeit or prohibited items.</li><li>Harassment of buyers or sellers through the chat system.</li><li>Attempting to bypass security measures or the fraud detection system.</li></ul><h5>5. Dispute Resolution</h5><p>Disputes between buyers and sellers are mediated by our support team. Decisions made by our admin team are final.</p>",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HelpCategoryID = 5,
                            IsPopular = false,
                            Title = "Terms of Service"
                        });
                });

            modelBuilder.Entity("FYP.Models.Entities.HelpCategory", b =>
                {
                    b.Property<int>("HelpCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("HelpCategoryID"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("IconClass")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("HelpCategoryID");

                    b.ToTable("HelpCategories");

                    b.HasData(
                        new
                        {
                            HelpCategoryID = 1,
                            DisplayOrder = 1,
                            IconClass = "shield-lock",
                            Name = "Account & Security"
                        },
                        new
                        {
                            HelpCategoryID = 2,
                            DisplayOrder = 2,
                            IconClass = "credit-card",
                            Name = "Payments"
                        },
                        new
                        {
                            HelpCategoryID = 3,
                            DisplayOrder = 3,
                            IconClass = "truck",
                            Name = "Orders & Shipping"
                        },
                        new
                        {
                            HelpCategoryID = 4,
                            DisplayOrder = 4,
                            IconClass = "arrow-return-left",
                            Name = "Returns & Refunds"
                        },
                        new
                        {
                            HelpCategoryID = 5,
                            DisplayOrder = 5,
                            IconClass = "file-text",
                            Name = "Policies & General"
                        });
                });

            modelBuilder.Entity("FYP.Models.Entities.IpFilter", b =>
                {
                    b.Property<int>("FilterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FilterID"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("AddedByAdminID")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FilterAction")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("FilterID");

                    b.HasIndex("AddedByAdminID");

                    b.ToTable("IpFilters");
                });

            modelBuilder.Entity("FYP.Models.Entities.Notification", b =>
                {
                    b.Property<string>("NotificationID")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("NotificationID");

                    b.HasIndex("UserID");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("FYP.Models.Entities.Order", b =>
                {
                    b.Property<string>("OrderID")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("BuyerID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeliveryID")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsRated")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("OrderID");

                    b.HasIndex("BuyerID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("FYP.Models.Entities.OrderItem", b =>
                {
                    b.Property<string>("OrderItemID")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("OrderID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ProductID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("OrderItemID");

                    b.HasIndex("OrderID");

                    b.HasIndex("ProductID");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("FYP.Models.Entities.Payment", b =>
                {
                    b.Property<string>("PaymentID")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("OrderID")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PaymentToken")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TransactionHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PaymentID");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("OrderID")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("FYP.Models.Entities.Product", b =>
                {
                    b.Property<string>("ProductID")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("AverageRating")
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("CategoryID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int");

                    b.Property<string>("SellerID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("StockLevel")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("TotalSales")
                        .HasColumnType("int");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("ProductID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("SellerID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = "PROD_001",
                            AverageRating = 4.9m,
                            CategoryID = "cat_tech_1",
                            Description = "Experience pure sound with industry-leading active noise cancellation. Features 30-hour battery life, touch sensor controls, and speak-to-chat technology.",
                            ImageHash = "SEED",
                            Price = 899.00m,
                            ReviewCount = 342,
                            SellerID = "seller_demo_1",
                            StockLevel = 45,
                            Title = "Wireless Noise-Cancelling Headphones Pro",
                            TotalSales = 1250,
                            WeightKg = 1.00m
                        },
                        new
                        {
                            ProductID = "PROD_002",
                            AverageRating = 4.8m,
                            CategoryID = "cat_tech_1",
                            Description = "Advanced health monitoring right on your wrist. Measure your blood oxygen level, take an ECG anytime, and track your daily activity.",
                            ImageHash = "SEED",
                            Price = 1299.00m,
                            ReviewCount = 890,
                            SellerID = "seller_demo_1",
                            StockLevel = 120,
                            Title = "Smart Fitness Watch Series 7",
                            TotalSales = 3400,
                            WeightKg = 1.00m
                        },
                        new
                        {
                            ProductID = "PROD_003",
                            AverageRating = 4.7m,
                            CategoryID = "cat_tech_1",
                            Description = "Tactile mechanical switches for ultimate gaming performance. Features customizable per-key RGB lighting and an aircraft-grade aluminum alloy frame.",
                            ImageHash = "SEED",
                            Price = 450.00m,
                            ReviewCount = 156,
                            SellerID = "seller_demo_1",
                            StockLevel = 3,
                            Title = "Mechanical Gaming Keyboard RGB",
                            TotalSales = 850,
                            WeightKg = 1.00m
                        },
                        new
                        {
                            ProductID = "PROD_004",
                            AverageRating = 4.9m,
                            CategoryID = "cat_tech_1",
                            Description = "Weighing only 63 grams, this mouse is designed for professional esports. Features a 25K DPI sensor and zero-additive PTFE feet for smooth gliding.",
                            ImageHash = "SEED",
                            Price = 320.00m,
                            ReviewCount = 512,
                            SellerID = "seller_demo_1",
                            StockLevel = 80,
                            Title = "Ultra-Light Wireless Esports Mouse",
                            TotalSales = 2100,
                            WeightKg = 1.00m
                        },
                        new
                        {
                            ProductID = "PROD_005",
                            AverageRating = 4.6m,
                            CategoryID = "cat_tech_1",
                            Description = "Stunning 4K resolution with 99% sRGB color accuracy. Factory calibrated for creators who demand perfect color representation and crisp text.",
                            ImageHash = "SEED",
                            Price = 1850.00m,
                            ReviewCount = 89,
                            SellerID = "seller_demo_1",
                            StockLevel = 15,
                            Title = "27-inch 4K IPS Creator Monitor",
                            TotalSales = 420,
                            WeightKg = 1.00m
                        },
                        new
                        {
                            ProductID = "PROD_006",
                            AverageRating = 4.9m,
                            CategoryID = "cat_tech_1",
                            Description = "Never run out of battery again. This high-capacity power bank supports 65W Power Delivery, allowing you to fast-charge your smartphone, tablet, and even your laptop on the go.",
                            ImageHash = "SEED",
                            Price = 150.00m,
                            ReviewCount = 1240,
                            SellerID = "seller_demo_1",
                            StockLevel = 250,
                            Title = "20,000mAh PD Fast Charge Power Bank",
                            TotalSales = 5600,
                            WeightKg = 1.00m
                        });
                });

            modelBuilder.Entity("FYP.Models.Entities.Refund", b =>
                {
                    b.Property<string>("RefundID")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("AdminResolution")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("IssueType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("OrderID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("PickupAddressID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PickupDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("RefundAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("RefundEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("RefundedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("RequestedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ReturnCourier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ReturnMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ReturnTrackingNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SellerNotes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("StripeRefundId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("RefundID");

                    b.HasIndex("OrderID");

                    b.ToTable("Refunds");
                });

            modelBuilder.Entity("FYP.Models.Entities.Review", b =>
                {
                    b.Property<string>("ReviewID")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("BuyerID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MediaUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("OrderID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ProductID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("ReviewID");

                    b.HasIndex("BuyerID");

                    b.HasIndex("OrderID");

                    b.HasIndex("ProductID");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("FYP.Models.Entities.SavedBankCard", b =>
                {
                    b.Property<string>("CardID")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Brand")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CardHolderName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ExpMonth")
                        .HasColumnType("int");

                    b.Property<int>("ExpYear")
                        .HasColumnType("int");

                    b.Property<string>("Fingerprint")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Last4")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<string>("PaymentToken")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("CardID");

                    b.HasIndex("UserID");

                    b.ToTable("SavedBankCards");
                });

            modelBuilder.Entity("FYP.Models.Entities.User", b =>
                {
                    b.Property<string>("UserID")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeviceHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("MFA_Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PaymentGatewayCustomerId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("SSMNumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("StoreName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TotpSecret")
                        .HasColumnType("longtext");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = "seller_demo_1",
                            CreatedAt = new DateTime(2026, 8, 14, 0, 24, 51, 688, DateTimeKind.Utc).AddTicks(4623),
                            DeviceHash = "SEED",
                            Email = "demo_seller@secureplatform.com",
                            IsDisabled = false,
                            MFA_Enabled = true,
                            Name = "Official Tech Store",
                            PasswordHash = "SEED_NO_LOGIN",
                            PhoneNumber = "0123456789",
                            Role = "Seller"
                        },
                        new
                        {
                            UserID = "admin_demo_1",
                            CreatedAt = new DateTime(2026, 8, 14, 0, 24, 51, 689, DateTimeKind.Utc).AddTicks(5379),
                            DeviceHash = "SEED",
                            Email = "demo_admin@secureplatform.com",
                            IsDisabled = false,
                            MFA_Enabled = true,
                            Name = "System Administrator",
                            PasswordHash = "SEED_NO_LOGIN",
                            PhoneNumber = "0123456789",
                            Role = "Admin"
                        },
                        new
                        {
                            UserID = "SYSTEM",
                            CreatedAt = new DateTime(2026, 8, 14, 0, 24, 51, 689, DateTimeKind.Utc).AddTicks(5383),
                            DeviceHash = "SEED",
                            Email = "system@secureplatform.com",
                            IsDisabled = false,
                            MFA_Enabled = false,
                            Name = "SYSTEM",
                            PasswordHash = "SEED_NO_LOGIN",
                            PhoneNumber = "0000000000",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("FYP.Models.Entities.UserDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Browser")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("DeviceHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("LastUsedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OS")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserID");

                    b.ToTable("UserDevices");
                });

            modelBuilder.Entity("FYP.Models.Entities.Wishlist", b =>
                {
                    b.Property<int>("WishlistID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("WishlistID"));

                    b.Property<string>("BuyerID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ProductID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("WishlistID");

                    b.HasIndex("BuyerID");

                    b.HasIndex("ProductID");

                    b.ToTable("Wishlists");
                });

            modelBuilder.Entity("FYP.Models.Entities.Address", b =>
                {
                    b.HasOne("FYP.Models.Entities.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FYP.Models.Entities.AuditLog", b =>
                {
                    b.HasOne("FYP.Models.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FYP.Models.Entities.BlacklistedImageHash", b =>
                {
                    b.HasOne("FYP.Models.Entities.User", "AddedByAdmin")
                        .WithMany()
                        .HasForeignKey("AddedByAdminID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddedByAdmin");
                });

            modelBuilder.Entity("FYP.Models.Entities.Cart", b =>
                {
                    b.HasOne("FYP.Models.Entities.User", "User")
                        .WithOne("Cart")
                        .HasForeignKey("FYP.Models.Entities.Cart", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FYP.Models.Entities.CartItem", b =>
                {
                    b.HasOne("FYP.Models.Entities.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FYP.Models.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FYP.Models.Entities.ChatMessage", b =>
                {
                    b.HasOne("FYP.Models.Entities.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FYP.Models.Entities.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("FYP.Models.Entities.Delivery", b =>
                {
                    b.HasOne("FYP.Models.Entities.Courier", "Courier")
                        .WithMany()
                        .HasForeignKey("CourierID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FYP.Models.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Courier");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("FYP.Models.Entities.DeliveryPricingRule", b =>
                {
                    b.HasOne("FYP.Models.Entities.Courier", "Courier")
                        .WithMany("PricingRules")
                        .HasForeignKey("CourierID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Courier");
                });

            modelBuilder.Entity("FYP.Models.Entities.FraudAlert", b =>
                {
                    b.HasOne("FYP.Models.Entities.Order", "Order")
                        .WithOne("FraudAlert")
                        .HasForeignKey("FYP.Models.Entities.FraudAlert", "OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("FYP.Models.Entities.HelpArticle", b =>
                {
                    b.HasOne("FYP.Models.Entities.HelpCategory", "Category")
                        .WithMany("Articles")
                        .HasForeignKey("HelpCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FYP.Models.Entities.IpFilter", b =>
                {
                    b.HasOne("FYP.Models.Entities.User", "AddedByAdmin")
                        .WithMany()
                        .HasForeignKey("AddedByAdminID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddedByAdmin");
                });

            modelBuilder.Entity("FYP.Models.Entities.Notification", b =>
                {
                    b.HasOne("FYP.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FYP.Models.Entities.Order", b =>
                {
                    b.HasOne("FYP.Models.Entities.User", "Buyer")
                        .WithMany("Orders")
                        .HasForeignKey("BuyerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buyer");
                });

            modelBuilder.Entity("FYP.Models.Entities.OrderItem", b =>
                {
                    b.HasOne("FYP.Models.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FYP.Models.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FYP.Models.Entities.Payment", b =>
                {
                    b.HasOne("FYP.Models.Entities.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("FYP.Models.Entities.Payment", "OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("FYP.Models.Entities.Product", b =>
                {
                    b.HasOne("FYP.Models.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FYP.Models.Entities.User", "Seller")
                        .WithMany("Products")
                        .HasForeignKey("SellerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("FYP.Models.Entities.Refund", b =>
                {
                    b.HasOne("FYP.Models.Entities.Order", "Order")
                        .WithMany("Refunds")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("FYP.Models.Entities.Review", b =>
                {
                    b.HasOne("FYP.Models.Entities.User", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FYP.Models.Entities.Order", "Order")
                        .WithMany("Reviews")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FYP.Models.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FYP.Models.Entities.SavedBankCard", b =>
                {
                    b.HasOne("FYP.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FYP.Models.Entities.UserDevice", b =>
                {
                    b.HasOne("FYP.Models.Entities.User", "User")
                        .WithMany("UserDevices")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FYP.Models.Entities.Wishlist", b =>
                {
                    b.HasOne("FYP.Models.Entities.User", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FYP.Models.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FYP.Models.Entities.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("FYP.Models.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("FYP.Models.Entities.Courier", b =>
                {
                    b.Navigation("PricingRules");
                });

            modelBuilder.Entity("FYP.Models.Entities.HelpCategory", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("FYP.Models.Entities.Order", b =>
                {
                    b.Navigation("FraudAlert")
                        .IsRequired();

                    b.Navigation("OrderItems");

                    b.Navigation("Payment")
                        .IsRequired();

                    b.Navigation("Refunds");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("FYP.Models.Entities.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("AuditLogs");

                    b.Navigation("Cart")
                        .IsRequired();

                    b.Navigation("Orders");

                    b.Navigation("Products");

                    b.Navigation("UserDevices");
                });
#pragma warning restore 612, 618
        }
    }
}
